[package]
name = "bbox-feature-server"
version = "0.6.2"
readme = "README.md"
description = "BBOX OGC API Features Service"
categories = ["science::geo"]
authors = ["Pirmin Kalberer <pirmin.kalberer@gmail.com>"]

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
homepage.workspace = true

[features]
html = ["bbox-core/html"]
stac = ["bbox-core/stac"]

[dependencies]
actix-web = { workspace = true }
async-trait = { workspace = true }
bbox-core = { path = "../bbox-core", version = "0.6.2" }
chrono = { workspace = true }
clap = { workspace = true }
dyn-clone = "1.0.6"
futures = { workspace = true }
geo-types = "0.7.13"
geozero = { workspace = true, features = [ "with-gpkg", "with-postgis-sqlx" ] }
log = { workspace = true }
minijinja = { workspace = true }
once_cell = { workspace = true }
rust-embed = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_urlencoded = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
test-log = "0.2.14"

[[bin]]
name = "bbox-feature-server"
path = "src/main.rs"
